{% set name = "knotifications" %}
{% set version = "5.66.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/knotifications-{{ version }}.tar.xz
  sha256: aad3697a35109fad49fa286b7837d382599478bac33151cd7991c760866c12c1

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('knotifications', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - xorg-libxext
    - qt
    - phonon
    - kconfig
    - kcodecs
    - kcoreaddons
    - kwindowsystem

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5Notifications.so

about:
  home: https://api.kde.org/frameworks/knotifications/html/index.html
  license: LGPL-v2.1-or-later
  license_family: GPL
  license_file: COPYING.LIB
  summary: 'Desktop notifications'
  description: |
    KNotification is used to notify the user of an event. It covers feedback and persistent events.
  dev_url: https://cgit.kde.org/knotifications.git/tree

extra:
  recipe-maintainers:
    - scopatz
